
spring.datasource.url=jdbc:mysql://mysql-1913e7fb-chakrithagreshma-e1ab.j.aivencloud.com:24749/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true